### ISSUE TITLE
Don't use `eval` in code

### ISSUE THREAD

**Issue by antony** [MakeNowJust/h.js#19]
The `h.js` minified code is fun, but having to use `eval` to parse it is an error which is caught by most good bundlers.

It would be good to remove the use of `eval` in https://github.com/MakeNowJust/h.js/blob/master/h.js#L25

**Comment by MakeNowJust** [comment]
impossible

**Comment by MakeNowJust** [comment]
@antony Note that you can expand h.js by [prepack](https://prepack.io). ([here](https://prepack.io/repl.html#LYewJgrgNgpgdDAHgBxAJwC4GcC8AKPZAGlwG04LkBdONGSAYxgKyIYEocA+PBnLOFmRQAlhl7t2cAFYgRAO15xUyPJKIAoAAZ4AFgC9dOAI5EAZkQw4A5NaIwcGfRmmkAPADIqAegDmbfQAtDwBiAE0GOAZdAEM0AGFwGABBcXYAXwBuQIB1PgB9fTx8-mkAPQA1LAAqdgrvergNaoAfAFVqvFIyqmqAfg627xbu3oAVdm8iYqIAdyJgdiKMAGocQLDZ9IBlBi4wgCVF6QABNtmVvyIwIO2wfbAARUD2Z6JbMY1Ofj7jHHz2AAuBh-fI5ND-fR-EHscpVWr1brVKh4CqkCptOAtODsfptKjtTHY9grAbeUgiYC+CAATywvWxzTGUxm80WyzWGy22zQ+2Abw+OWAODQeByUCIyBwpAACvoAN6zXQiKAHPDC7xlLo9fp1ABGeBiWBp8gYAFkNNK2ogAEwABjaGF6ABkzBBTRgRCB5G09S1necVu08HA8WNSNb7Y7evoxi09XQYgBrFoMGIYaKpqBGrCp73OrAYFoaT3yCAwdgtMAwMwxaBFsAgFowKBYGAtMwKGJQKA0jvoDtoEDADvuhie70tERmKfAVCYFqwIuF9MiBgtLAaCDIGBoDezMSZjDK3MYNB9gBucRaSpV7YPx5ahtmMTEqaN7erS-bSHnRaQGAwPIYC5iIGjyAWGAxKaMAgGY7B9C08gwLMLRwS0dAYBAaDyC0x5DqhGA0ju6EXnIYAtDSIgtmAYy+i0FR6s6dqkIgAAaVCkDEAC0ZjJNxABibRgBoVBBme5Ydt2bZIdAUAtO61adshFEAHIxKpLQAJLyMpYg0uw9EBnAwlBr6zGkCAADyeoAEIygMYArMZwnNAh7DOqQMAAKKcdxKxUI5KzuU+FS2jaLTWB5AZtKMxJ4gA7Ni1RxhUJnpSMaLypkRB9ICBL6JWXRNIZVDpDKT7cdxIwBaQAUtB4HgjC0nEtf6bhuC0XDdYhpD+UMACkTVlG4XAEoMuo4IhAB+IwAIQ4FQU1TUVGikAAJOcYlmjgbQ1KQeCBFQYwAARnWdT4vE+cA7UMpDVEMx2TAgiAwAwvDGOdEyNQA0gAjOdgNnXa3F-VQc2WtY6TWC0HYLX9Yy4AAUgAEgA4kDOQo39NqBXNeDyAqqw4Ac2Myis1jbFgXCBNYmSzOdyqqoDBM4JqeCA90om6hiWKHZWFRhMyQMvW9xhjI1c3yKQf0rDaMrI9LaM5MTBzndLAPneTBOkDaKyA7jGh9JTyBcG0YQACLbCIXDWCseBQDgQO6KYf0q8RsFmA77C22g1i-DYdhQBT50W1FgOAn8UAy1QRDR3aYkaNYVum481hjICBzS7jYyZEDxME30WekAnJA4EjSsZzApi4LYX0UxbgNQ+waiAngqsoxof3k-9etg7D2Ny1QQMjydjWELrS02HA1iNZqe3VOt53eHAgGFkD-0yuP88aPth0+KvMCFqY2OjyPQ84Cjeu44HCFzf9YPnZf8uAn9lajy08+btUgIr2vGDiyLlfGUgIgaBG2GEaw+Rzr5HyEmfIF4sD5GQMgQGcFrCkGAHAc6ChqyICsmYH6uMiCa3OnLdgol0j7FJvLZ4OQpTAByBzQGZhfqkJBmDHANhoaA0amYKqLRzotBRglFYnCbDylnh4MwgMVgrC+DkIhQ8B6iP7oIwG2M7Rb3Oh4UU512CZDQIDGAWEcLMJOsAPopBAarFJmDHIgNUYaDRuwKggJVjVzGOkFuSxuBA2MHgLA0hsFnToKgs62YGBnyBgcbwgRAYAB0tBhASeteUgMcjsE0BUPAbQ2gJISRMdg2w3BCGgm0IGto7QMCgOdHMT8DjMGiWdR46QLYyioOwM00S8B9GdGaQEGgfp4BRkjAQWBRAMFJsAUgaME5wFgPIXwx4LZuG8GU+QXAtC0BgMIGITA8DeASVgK4thJCcC4DAK8UBAmSDwFoC2aNRlpKTtYE63hOjxHYCde0f0ACs3FfkAA4TpjG2ObNo2xkhjCsidAARGaZMMBVIgFmEjCAhY4UnR+mILA7oYDVG8OkH6-SZSPAONsOiFQchhECNIYw+gtAGI0EAA))

**Comment by MakeNowJust** [comment]
@antony What is **most good bundler**? I tried **most good bundlers** I know (webpack, parcel, rollup), but every bundlers do not cause an error.

**Comment by antony** [comment]
Here's what rollup has to say:

```

src/routes/event/index.html changed. rebuilding...
• server
Use of eval is strongly discouraged, as it poses security risks and may cause issues with minification
23: G)]:t+eqT})()z=>     q(sj.   rep   lac             R/Z    \`Y\${    W),
24: V(UU\\T))S<spanU     x20cl   ass   =Re(           Q}DP])M         (?LM:
25: K(HJs.slicRHm[G0].lengthD</span>`.replace(/\s/g,'')))=>eval(s))(`DGHJ${
                                                           ^
26: '' /*(C) 2015-2018 TSUYUSATO "MakeNowJust" Kitsune*/}KLMPQRSTUVWYZjqz`)
• client
Use of eval is strongly discouraged, as it poses security risks and may cause issues with minification
23: G)]:t+eqT})()z=>     q(sj.   rep   lac             R/Z    \`Y\${    W),
24: V(UU\\T))S<spanU     x20cl   ass   =Re(           Q}DP])M         (?LM:
25: K(HJs.slicRHm[G0].lengthD</span>`.replace(/\s/g,'')))=>eval(s))(`DGHJ${
                                                           ^
26: '' /*(C) 2015-2018 TSUYUSATO "MakeNowJust" Kitsune*/}KLMPQRSTUVWYZjqz`)
```

which is a bit annoying on every reload!

**Comment by antony** [comment]
In fact, I've just realised that you don't include the original source code in your github repository. This would be the ideal, since that way my bundler could handle minification.

Why isn't the original source in here? Where is it?

**Comment by MakeNowJust** [comment]
@antony I just published `h.js@4.1.0`. It adds a hack to prevent rollup warning. Please try it.

**Comment by antony** [comment]
@MakeNowJust oh boy, a warning suppression! That ascii art is important to you huh? :D

Thanks :>
